### PR TITLE
cgo & fix compile error for typo

### PR DESCRIPTION
**Pull request by carbin-gun**

### CODE REVIEW

**Comment by DoomHammer** [comment]
Please check #8

**Comment by kontsevoy** [comment]
Mmm... why do we need to explicitly set CGO for building teleconsole?

**Comment by carbin-gun** [comment]
you can check this `https://github.com/gravitational/teleport/pull/612`.
you have a dependency for `github.com/gravitational/teleport/lib/utils`.in the utils package.the shell.go has an explicit C module usage

**Comment by kontsevoy** [comment]
@carbin-gun so you were getting compile errors? that file doesn't require global CGO flag to be on.

**Comment by carbin-gun** [comment]
If no CGO flag ,the file can't be compiled into your binary code. your repo code will get a compile error of course.what would you do for CGO necessity from your dependencies?

the following the the make output without `CGO_ENABLED`
```
$ make
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C version
go build -i -ldflags -w -o out/teleconsole
# github.com/gravitational/teleport/lib/client
../teleport/lib/client/api.go:1185: undefined: "github.com/gravitational/teleport/lib/utils".GetLoginShell
# github.com/gravitational/teleport/lib/srv
../teleport/lib/srv/exec.go:114: undefined: "github.com/gravitational/teleport/lib/utils".GetLoginShell
../teleport/lib/srv/exec.go:162: undefined: "github.com/gravitational/teleport/lib/utils".GetLoginShell
make: *** [out/teleconsole] Error 2
```

**Comment by kontsevoy** [comment]
@carbin-gun I see now. Teleconsole needs to be updated with the latest Teleport. One solution would be to vendor Teleport in. Stay tuned, we'll add it.

**Comment by carbin-gun** [comment]
Yeah, it's a good practice to vendor to maintain the consistency between your code and the dependencies. But as for my opinion, the vendoring technology will not solve the problem.  because vendoring can't still resolve the CGO thing. you still have to enable the CGO_ENABLED flag .

**Pull request closed without merging**
